version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=edu-db-plug
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: .
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/edu-db-plug
      - JWT_SECRET=your_jwt_secret_here
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  mongo-data:
    driver: local
